browserConfig:
  driverEnum: CHROME

environment:
  prod:
    appUrl: http://automationpractice.com/index.php
    active: true
    waitTime: 15

  init:
    appUrl: http://automationpractice.com/index.php
    active: false
    waitTime: 15






